name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Use a stable Node version

      # Use a dedicated action to build and deploy Storybook
      - name: Build and Deploy Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static # The default output directory for a Storybook build
